services:
  - type: web
    name: love-website-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 10000
      - key: LOCAL_TZ
        value: Asia/Kolkata
